name: BulkRNASeqWorkflow_NIDAP
channels:
  - file:///gpfs/gsfs9/users/BIDS-HPC/public/software/nidap_hpc_environment_twin/local_channel/
  - bioconda
  - conda-forge
dependencies:
  - r-base=4.1.3
  - bioconductor-fgsea=1.20.0
  - r-UpSetR=1.4.0
  - r-patchwork=1.1.2
  - r-VennDiagram=1.7.3
  - r-htmlwidgets=1.6.2
  - r-gridGraphics=0.5-1
  - r-RColorBrewer=1.1-3
  - r-dendextend=1.17.1
  - bioconductor-complexheatmap=2.10.0
  - r-dendsort=0.3.4
  - r-colorspace=2.1-0
  - r-plotly=4.10.1
  - r-RCurl=1.98-1.12
  - r-tidyr=1.3.0
  - r-tibble=3.2.1
  - r-dplyr=1.1.1
  - r-gtable=0.3.3
  - r-reshape2=1.4.4
  - r-gridExtra=2.3
  - bioconductor-sva=3.42.0
  - bioconductor-biocparallel=1.28.3
  - bioconductor-genefilter=1.76.0
  - r-mgcv=1.8-42
  - r-nlme=3.1-162
  - r-stringr=1.5.0
  - bioconductor-edger=3.36.0
  - r-ggplot2=3.4.2
  - bioconductor-limma=3.50.3
  - r-evaluate=0.20
  - r-uuid=1.1-0
  - r-sparkr=3.2.1
  - r-jsonlite=1.8.4
  - r-futile.logger=1.4.3
