name: DSPWorkflow_NIDAP_v1_3_1
channels:
  - file:///rstudio-files/ccbr-data/users/RH/NIDAP_HPC_Env_Mirror/local_channel/
  - bioconda
  - conda-forge
dependencies:
  - r-dspworkflow==1.3.1
  - r-base==4.1.3
  - r-backports==1.4.1 
  - bioconductor-biobase==2.54.0 
  - bioconductor-biocgenerics==0.40.0 
  - bioconductor-nanostringnctools=1.2.0 
  - bioconductor-geomxtools==3.1.1 
  - bioconductor-complexheatmap==2.10.0 
  - bioconductor-spatialdecon==1.4.3 
  - r-tidyverse==1.3.2 
  - r-cowplot==1.1.1 
  - r-dplyr==1.0.9 
  - r-ggforce==0.3.4 
  - r-ggplot2==3.3.6 
  - r-ggiraph==0.7.10=r41h03ef668_0
  - r-gridExtra==2.3 
  - r-gtable==0.3.0 
  - r-knitr==1.40 
  - r-patchwork==1.1.2 
  - r-reshape2==1.4.4 
  - r-rmpfr==0.8-9 
  - r-rtsne==0.16 
  - r-scales==1.2.1 
  - r-tibble==3.1.8 
  - r-tidyr==1.2.1 
  - r-umap==0.2.9.0 
  - r-pheatmap==1.0.12
  - r-xlsx
  - r-stringr
  - r-devtools
  - r-lintr
  - r-renv
  - r-jsonlite
  - r-pkgdown
